### ISSUE TITLE
Issue processing an input file

### ISSUE THREAD

**Issue by Alejobep** [keurfonluu/toughio#110]
Hi,

I have been using toughio to process some files from T2Well without issue.

However, there is a simulation file where I have been able to process the mesh, the output file but not the input file.

Although I have briefly explored the files and the functions I still do not know what is causing the issue.

**Full code that generated the error**

```python
input_fn = r'35bar_mod-cond.txt'

ip = toughio.read_input(input_fn, file_format='tough')
```

**Full error message**

```python
ValueError                                Traceback (most recent call last)
File ~/toughio/_io/input/tough/_read.py:180, in read_buffer(f, label_length, eos)
    179 elif line.startswith("INCON"):
--> 180     incon, flag = _read_incon(fiter, label_length, eos)
    181     parameters.update(incon)

File ~/toughio/_io/input/tough/_read.py:861, in _read_incon(f, label_length, eos)
    859 if line.strip() and not line.startswith("+++"):
    860     # Record 1
--> 861     data = read_record(line, fmt2[label_length])
    862     label = data[0]

File ~/toughio/_io/input/tough/_helpers.py:306, in read_record(data, fmt)
    305 tmp = tmp if token[-1] == "S" else tmp.strip()
--> 306 out.append(token_to_type[token[-1]](tmp) if tmp else None)
    307 i += n

ValueError: invalid literal for int() with base 10: '999.9'
```

I am enclosing the input file here
[35bar_mod-cond.txt](https://github.com/keurfonluu/toughio/files/8572742/35bar_mod-cond.txt)

**System information**

* Operating system: Red Hat Enterprise Linux 7
* Python installation (Anaconda, system, ETS): system
* Version of Python: 3.8.11
* Version of this package: 1.9.0

**Comment by keurfonluu** [comment]
Hi @Alejobep,

Thanks for reporting the issue. It should be fixed now. Please update to toughio v1.9.1: `pip install toughio -U`.
I also fix another issue thanks to your input file.

If the issue is indeed resolved, feel free to close it.

**Comment by Alejobep** [comment]
Thanks a lot for fixing this. It worked fine.

I have a follow up question and I wonder if I should open a new thread or I can continue with this.

I have been using **toughio** for **T2well** simulations and it has worked fine. At this stage I am not sure if this issue is related to the fact that I am not using **toughio** for its intended purpose (TOUGH2/TOUGH3) or if it is an actual issue of **toughio**

When I intend to extract results from T2WELL main output file and reformat as a TOUGH3 CSV output file:
```
toughio-extract 35bar_mod-cond.out MESH
```

I get the following traceback error

```python
Traceback (most recent call last):
  File "~/toughio/_cli/_extract.py", line 52, in extract
    [parameters["elements"][label]["center"] for label in output[-1].labels]
  File "~/toughio/_cli/_extract.py", line 52, in <listcomp>
    [parameters["elements"][label]["center"] for label in output[-1].labels]
KeyError: '118  '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/toughio-extract", line 8, in <module>
    sys.exit(extract())
  File "~/toughio/_cli/_extract.py", line 68, in extract
    raise ValueError(
ValueError: Elements in '35bar_mod-cond.out' and 'MESH' are not consistent.
```

I am enclosing the output and MESH files here
[MESH.txt](https://github.com/keurfonluu/toughio/files/8609252/MESH.txt)
[35bar_mod-cond.txt](https://github.com/keurfonluu/toughio/files/8609253/35bar_mod-cond.txt)

**Comment by keurfonluu** [comment]
My bad. I've fixed the issue in the hotfix branch. However, I will not release that hotfix right away as I want to fix another issue beforehand. Please update toughio from that branch if you don't want to wait.

Note that I have never used T2WELL, so I don't know how well toughio works for that simulator.

**Comment by Alejobep** [comment]
The hotfix branch worked fine. Thank you!! Looking forward to see the updated version.

T2WELL works relatively fine with TOUGHIO. It recognized 100% of the input file and reproduced it.
The main difference in terms of files is that it produces 2 new files. The rest of the output is close compatible with TOUGH2/TOUGH3.

I saw that some of my input files, had float numbers with 4 or higher significant figures. I noticed that when reading my input file and printing a new one without doing anything, the precision of these numbers was rounded to 3 significant figures. It was not a big deal but justa wanted to mention it to you.

**Comment by keurfonluu** [comment]
Yes, I know. That's a lazy design choice since that way, I am sure that the format is correct.
I will see what I can do. I already have something in place to automatically use floating point or scientific notation depending on the length of the representation of a real value. Currently, it's only used for the coordinates in block ELEME, but it may be better to expand it to other properties.

**Comment by keurfonluu** [comment]
I've uploaded the fix to PyPI. Feel free to close the issue if it's solved!

**Comment by Alejobep** [comment]
Thanks!!
