### ISSUE TITLE
Importing mesh from Abaqus

### ISSUE THREAD

**Issue by Alejobep** [keurfonluu/toughio#114]
Hi,

I have generated a simple mesh from Abaqus to be used with TOUGH. However, there must be something I am missing in my mesh defintion because I am not able to use it.

```toughio``` is able to read the mesh and I am able to visualize it using ```pyvista```.

However as I attempt to write the ```MESH``` file with the ```mesh.write_tough()``` method I get the following error: ```KeyError: 'triangle'```.

I have zipped the OBJ file from Abaqus here: [test.zip](https://github.com/keurfonluu/toughio/files/8799052/test.zip)

This is my code:

```python

import pyvista

p.show()

abaqus_mesh = r'test.obj'

mesh = toughio.read_mesh(filename=abaqus_mesh, format='abaqus')

pyvista.set_plot_theme("document")

p = pyvista.Plotter(window_size=(800, 800))
p.add_mesh(
    mesh=mesh.to_pyvista(),
    show_edges=True,
)
p.view_xz()
```

![image](https://user-images.githubusercontent.com/49291809/171010369-0cdb00f7-86ea-4d50-a6ca-7b6f4f333033.png)

The I proceed to write the ```MESH``` file:

```python
mesh.write_tough('MESH')

```

And this is the traceback error.

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_33132\2540450123.py in <module>
----> 1 mesh.write_tough('mesh')

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_mesh.py in write_tough(self, filename, **kwargs)
    375 
    376         """
--> 377         self.write(filename, file_format="tough", **kwargs)
    378 
    379     def write_incon(self, filename="INCON", eos=None):

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_mesh.py in write(self, filename, file_format, **kwargs)
    513         from ._helpers import write
    514 
--> 515         write(filename, self, file_format, **kwargs)
    516 
    517     def plot(self, *args, **kwargs):

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_helpers.py in write(filename, mesh, file_format, **kwargs)
    173             mesh = deepcopy(mesh)
    174             mesh.cell_data = {k: mesh.split(v) for k, v in mesh.cell_data.items()}
--> 175         _writer_map[fmt](filename, mesh, **kwargs)
    176     else:
    177         mesh = mesh.to_meshio()

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\tough\_tough.py in write(filename, mesh, nodal_distance, material_name, material_end, incon, coord, eos, gravity)
     64     nodes = mesh.centers
     65     materials = mesh.materials
---> 66     volumes = mesh.volumes
     67     boundary_conditions = (
     68         mesh.cell_data["boundary_condition"]

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_mesh.py in volumes(self)
    801     def volumes(self):
    802         """Return volumes of cell in mesh."""
--> 803         return _volumes(self)
    804 
    805     @property

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_properties.py in _volumes(mesh)
    127     out = []
    128     for cell in mesh.cells:
--> 129         tetras = np.vstack([c[meshio_type_to_tetra[cell.type]] for c in cell.data])
    130         tetras = mesh.points[tetras]
    131         out.append(

c:\Appl\tough_env\lib\site-packages\toughio\_mesh\_properties.py in <listcomp>(.0)
    127     out = []
    128     for cell in mesh.cells:
--> 129         tetras = np.vstack([c[meshio_type_to_tetra[cell.type]] for c in cell.data])
    130         tetras = mesh.points[tetras]
    131         out.append(

KeyError: 'triangle' 
```

**System information**

* Operating system: Windows 10
* Python installation (Anaconda, system, ETS): Anaconda
* Version of Python: 3.7
* Version of this package: 1.10

**Comment by keurfonluu** [comment]
Hi @Alejobep ,

TOUGH uses the finite-volume method to solve the heat and flow equations. The keyword here is "volume" meaning that it requires a mesh with 3D cells (tetrahedron, pyramid, wedge or hexahedron). Your mesh is a 3D surface mesh made of triangle cells (i.e., it's hollow), thus cannot be used in TOUGH.

**Comment by Alejobep** [comment]
Thanks for your reply. It is strange because I have made other meshes and verified they are not a 3D surfcae with triangle cells.

![image](https://user-images.githubusercontent.com/49291809/171172568-425c7735-0559-4a1a-bcd4-52c7f4169995.png)

However, I wonder if I am exporting it the wrong way because as I save the file shown above as OBJ file and load it into toughio, I get the following view. I know this is beyond the purpose of this forum, but would you happen to know what is the correct way of exporting a mesh from abaqus?

![image](https://user-images.githubusercontent.com/49291809/171176903-34883831-0289-4746-a596-04caf45f484f.png)

**Comment by Alejobep** [comment]
Ok, nevermind. I have found the error. So, assistance is no longer needed. Thanks a lot

**Comment by Alejobep** [comment]
Just one extra questions. Is there a way to get the materials from Abaqus?

**Comment by keurfonluu** [comment]
I don't have Abaqus so I wouldn't know how to export materials from Abaqus. Do you have a sample file?

**Comment by Alejobep** [comment]
Hi again. I sort of figured it out. In Abaqus you can assign materials to specific regions of your mesh.
Those are stored in the *.inp file (abaqus mesh file) as point sets.
When **toughio** reads the abaqus file, such point sets are stored in the `point_sets`  property of the `mesh` object.
Your code has this method `point_data_to_cell_data()` that maps out the indexes of the cells linked to the points in the point_sets array.

With that was very simple just to assign materials to my mesh.

Toughio has been definitely a lifesaver, thanks a lot for the effort. I understand it explots the already built features of pyvista and meshio, but the fact that toughio exists is great!!

I am enclosing a simple mesh with an arbitrary zonation thta covers only a portion of the mesh.
[Job-1.zip](https://github.com/keurfonluu/toughio/files/8830500/Job-1.zip)
