### ISSUE TITLE
Time-independent Dirichlet boundary conditions

### ISSUE THREAD

**Issue by Alejobep** [keurfonluu/toughio#115]
Hi,

I wonder if there were chances of processing files with Dirichlet boundary conditions defined by using inactive elements.

In the [attached file](https://github.com/keurfonluu/toughio/files/8877147/case2.zip) you can see that in line 249 there is an inactive element named ``ina`` and no other parameter specified. That element is processed as a zero volume element adn defines any subsequent element as a Dirichlet boundary without needing to expand the volume in ``ELEME`` by several orders of magnitude and modifying the nodal distances in the ``CONNE`` section.

As stated in the TOUGH2 manual, it is _"an alternative and more elegant implementation"_ for time-independent Dirichlet boundary conditions.

For processing purposes it results in just ignoring rows with zero or undefined volume.

My workaround so far has been creating copies of both the input and MESH files, deleting the line in ELEME section where the inactive cell is, and used those modified files for processing in ``toughio``. However, this workaround does not work if I want to use the ``toughio-extract`` functionality.

**Comment by keurfonluu** [comment]
Hi,

Yeah, `toughio` currently does not support inactive elements because this feature is no longer supported in TOUGH3.

What's the error raised with `toughio-extract`? I guess it doesn't work because the inactive element does not have any coordinate.
Do you have a sample output file to work with?

**Comment by Alejobep** [comment]
Thansk for your reply. I was unware of such improvements in TOUGH3. I am using only T2Well and TOUGH2.

I am enclosing a [zip file](https://github.com/keurfonluu/toughio/files/8884696/Case2_brine_Dirichlet.zip) including both input, output and MESH files. Thanks

Regarding the error, it is certainly when readinf the MESH

```python
Traceback (most recent call last):
  File "~/bin/toughio-extract", line 8, in <module>
    sys.exit(extract())
  File "~/lib64/python3.8/site-packages/toughio/_cli/_extract.py", line 36, in extract
    parameters = read_mesh(
  File "~/lib64/python3.8/site-packages/toughio/_mesh/_helpers.py", line 94, in read
    mesh = _reader_map[fmt](filename, **kwargs)
  File "~/lib64/python3.8/site-packages/toughio/_mesh/tough/_tough.py", line 21, in read
    mesh = read_input(filename, file_format="tough", label_length=label_length)
  File "~/lib64/python3.8/site-packages/toughio/_io/input/_helpers.py", line 80, in read
    return _reader_map[fmt](filename, **kwargs)
  File "~/lib64/python3.8/site-packages/toughio/_io/input/tough/_read.py", line 45, in read
    out = read_buffer(f, label_length, eos)
  File "~/lib64/python3.8/site-packages/toughio/_io/input/tough/_read.py", line 196, in read_buffer
    raise ReadError("failed to parse line {}.".format(fiter.count))
toughio._exceptions.ReadError: failed to parse line 103.
```

.

**Comment by keurfonluu** [comment]
Hi @Alejobep,

Thanks for your files. It "should" be fixed now (I haven't run extensive tests, to be honest).
Please update to toughio v1.10.1: `pip install toughio -U`.

You shouldn't have any issue running `toughio-extract`. For `toughio-export`, I added a new option `--ignore-elements` that allows you to, obviously, ignore some elements (if mesh is not provided, i.e., if triangulation/voxelization is performed from the coordinates):

```
toughio-export OUTPUT_ELEME.csv --ignore-elements AAA00 AAA01 AAA02
```

In your case, I think the following command should do the trick:

```
toughio-export OUTPUT_ELEME.csv --ignore-elements "ina 0" --origin 0 0 0
```

Hope the results are correctly exported!

**Comment by Alejobep** [comment]
Thanks. It seems to work fine. I just have a couple of questions about pyvista.
So far I have been using Paraview to visualize my `vtk` file from `toughio-export`.
However, I am not sure what is the deal with Paraview but I am not getting all my time steps visualized. 
In paraview I get the following warning:
```linux
Warning: In /builddir/build/BUILD/ParaView-v4.4.0-source/VTK/IO/Legacy/vtkDataReader.cxx, line 490
vtkDataSetReader (0x45aede0): Reading file version: 4.2 with older reader version 4.0

Warning: In /builddir/build/BUILD/ParaView-v4.4.0-source/VTK/IO/Legacy/vtkDataReader.cxx, line 490
vtkUnstructuredGridReader (0x45ea650): Reading file version: 4.2 with older reader version 4.0

```

Although my simulation has 19 time steps, Paraview only shows 10 and the time stamp goes from 0 to 1 (t=0, 0.1111, 0.2222, ..., 1.0).

So, assuming there is something wrong with my installataion of Paraview, I decided to go back to pyvista in toughio.
To do so I typed the following:

```python
mesh_inp = toughio.read_mesh("MESH", file_format='tough')
points = [v["center"] for v in mesh_inp["elements"].values()]
mesh = toughio.meshmaker.voxelize(points, origin=[0.0, 0.0, 0.0])
mesh.read_output('OUTPUT_ELEME.csv', time_step=1, connection=True)
```

However I also got an error here. At the beginning I thougth it was about the inactive cells so I tested a simpler MESH and the result was the same.
[These are the files](https://github.com/keurfonluu/toughio/files/8941017/Case2.zip)

```python
File ~/python3.8/site-packages/toughio/_mesh/_mesh.py:449, in Mesh.read_output(self, file_or_output, time_step, connection)
    446     if len(out.labels) != self.n_cells:
    447         raise ValueError()
--> 449     out = reorder_labels(out, self.labels)
    450     self.cell_data.update(out.data)
    451 elif out.type == "connection":

File ~/python3.8/site-packages/toughio/_io/output/_common.py:38, in reorder_labels(data, labels)
     35     raise ValueError()
     37 mapper = {k: v for v, k in enumerate(data.labels)}
---> 38 idx = [mapper[label] for label in labels]
     39 data.labels[:] = data.labels[idx]
     41 for k, v in data.data.items():

File ~/python3.8/site-packages/toughio/_io/output/_common.py:38, in <listcomp>(.0)
     35     raise ValueError()
     37 mapper = {k: v for v, k in enumerate(data.labels)}
---> 38 idx = [mapper[label] for label in labels]
     39 data.labels[:] = data.labels[idx]
     41 for k, v in data.data.items():

KeyError: 'A11 0'
```

**Comment by keurfonluu** [comment]
Hi @Alejobep,

Your ParaView version is quite old, can you try with the most recent version (5.10.1)? I have 19 time steps with this version.
If I remember correctly, currently, `mesh.read_output` only supports mesh generated by `toughio` as it does not use the same naming convention as TOUGH.

**Comment by Alejobep** [comment]
Thanks you.
I have checked the data on my windows machine. On Redhat I cannot have a newer version of Paraview.
Now I have installed version 5.10.1 on Windows. As I load the vtk file I get no warnings/errors, but I do not get the time steps.
[These are the output files I get](https://github.com/keurfonluu/toughio/files/8965670/toughio_test.zip)
And below is a snapshot of how the time inspector looks like. Does my vtk file has all the data on it?
![image](https://user-images.githubusercontent.com/49291809/175260715-22ee8814-96e6-40a1-9edd-572f7c8b37c7.png)

**Comment by keurfonluu** [comment]
The VTK format cannot hold multiple time steps, only XDMF can:

```
toughio-export OUTPUT_ELEME.csv -f xdmf
```

**Comment by Alejobep** [comment]
Thanks again. It works well, I got confused about the the `vtk `and `xdmf` thing, I am not familiar with these formats at all.
The data is well displayed but I definitely needed to use the newer version of Paraview. The old one does not display the data correctly.
