### ISSUE TITLE
I am not sure if this feature exists or not

### ISSUE THREAD

**Issue by Alejobep** [keurfonluu/toughio#118]
Are there alternatives to reset the labels of each element in the mesh.
If one builds a mesh in `pyvista` or `gmsh` I see that toughio assigns some default label for each element.

Are there ways to change the name of a single element, or assign the label names following a personalized set of labels?

There are two situations where I can see this could help:

- In T2Well the element at the top of the well needs to have the character `*` at the beginning of the element label.
- When running sample cases, where tehre is no infor about the mesh, the user could build a mock mesh and assign the element labels based on the sample case elements. This coudl work where the vozelixe method falls short. For instance, to visualize results of cases with simple radial grids, it is easier to create a simple radial mesh with the same amount of elements and re-assign the element labels.

**Comment by keurfonluu** [comment]
Hi @Alejobep,

Yeah, I am not familiar with T2WELL so I kinda overlooked this feature.
I've implemented a method `mesh.set_cell_labels` in the new version v1.10.3. Is this what you expected?

I am still not entirely sure what would be the best way to implement it in the command line program `toughio-export`.

**Comment by Alejobep** [comment]
Thanks, that helps a lot. I have made use of it.

I have a rather silly question. Up until now I have been using already-made files. Now I wanted to build a case from scratch following your both tutorials. However I could not see how I could incorportate both the INCON and MESH data into the `write_input` case.

On a related note, if I want to set a boundary condition with large volume, it seems I can do that if I have the meshs incorporated within the parameters read by read_input. However I cannot modify the volume property in the mesh class.
Thanks

**Comment by keurfonluu** [comment]
You can use the keywords `"initial_conditions"`, "`elements`" and "`connections`". But in that case, you have to manually define your mesh which is usually not recommended. Also, I prefer to have the main input file, MESH and INCON as three separated files because MESH and INCON can be really large.

To set Dirichlet boundary conditions, use the method `mesh.add_cell_data` as described in the example. Then, use the method `mesh.write_tough` to export MESH (and INCON, if desired) which will automatically increase the volume with fixed parameters and set the nodal distances to a small value (per TOUGH user guide). The reason I don't allow changing the volumes is that this method is preferred to set the boundary conditions (and changing the volume is not enough, you have to change the nodal distances as well).

**Comment by geowomen** [comment]
> You can use the keywords `"initial_conditions"`, "`elements`" and "`connections`". But in that case, you have to manually define your mesh which is usually not recommended. Also, I prefer to have the main input file, MESH and INCON as three separated files because MESH and INCON can be really large.
> 
> To set Dirichlet boundary conditions, use the method `mesh.add_cell_data` as described in the example. Then, use the method `mesh.write_tough` to export MESH (and INCON, if desired) which will automatically increase the volume with fixed parameters and set the nodal distances to a small value (per TOUGH user guide). The reason I don't allow changing the volumes is that this method is preferred to set the boundary conditions (and changing the volume is not enough, you have to change the nodal distances as well).

Hello Keurfonluu,

Could you please guide me on how to separate the INCON file from the MESH file? 

Thank you for your guidance.

**Comment by keurfonluu** [comment]
Hi @geowomen,

MESH and INCON are in different files by default. What do you mean exactly?

Anyway, given a parameter dictionary, you can export a selection of blocks with the option `block` (please refer to the [documentation](https://keurfonluu.github.io/toughio/api/io.html#toughio.write_input)):

```python
parameters = toughio.read_input("my_input_file.inp")
toughio.write_input("INCON", parameters, block="incon")  # write out INCON block only if key "initial_conditions" exists
toughio.write_input("MESH", parameters, block="mesh")  # write out ELEME and CONNE blocks only if keys "elements" and "connections" exist
```
