### ISSUE TITLE
How to read an existing 'MESH' file and convert it to be a Mesh object

### ISSUE THREAD

**Issue by tjuCJC** [keurfonluu/toughio#124]
I find it's hard to complete a visualization for an existing 'MESH' file when using Paraview. I can't convert the ’MESH‘ file to be the format of .vtk or .vtu  with the method [toughio.read_input()](url) or [toughio.read_mesh()](url), the return value of method above is 'dict' instead of class [Mesh](url)，whereas the return value of these method on a .f3grid file is class [Mesh]([url]).  Some attempt on this  question is as follow,

```
import toughio, pyvoro
filename = 'F:/mesh_t/f2t/f6.f3grid'
mesh = toughio.read_mesh(
   filename,
   file_format="flac3d",
)
mesh.write_tough()

print(type(mesh))

mesh2 = toughio.read_input('MESH',file_format="tough")
print(type(mesh2))

mesh3 = toughio.read_mesh('MESH', file_format='tough')
print(type(mesh3))

```
and the return value is 
```
<class 'toughio._mesh._mesh.Mesh'>
<class 'dict'>
<class 'dict'>
```
according to the source code, I find that in "toughio/_io/input/tough/_read.py" ,  [read()](url) function will read 'MESH' and return a dict when the file_format is "tough"
```
def read(filename, label_length=None, eos=None, simulator="tough"):
    """
    Read TOUGH input file.
    Parameters
    ----------
    filename : str, pathlike or buffer
        Input file name or buffer.
    label_length : int or None, optional, default None
        Number of characters in cell labels.
    eos : str or None, optional, default None
        Equation of State.
    Returns
    -------
    dict
        TOUGH input parameters.
    """
    if not (label_length is None or isinstance(label_length, int)):
        raise TypeError()
    if isinstance(label_length, int) and not 5 <= label_length < 10:
        raise ValueError()
    if simulator not in {"tough", "toughreact"}:
        raise ValueError()

    with open_file(filename, "r") as f:
        out = read_buffer(f, label_length, eos, simulator)

    return out
```
so how can I convert my "MESH" file into Mesh object, and do some visualization. May I get the coordinate value of x,y,z of my 'MESH' file and set them to be the input value of [toughio.meshmaker()](url) method to get a class `Mesh`?

**Comment by keurfonluu** [comment]
Hi @tjuCJC,

Please refer to issue #91.

**Comment by tjuCJC** [comment]
Thank you so much @keurfonluu, I can convert the 'MESH' file into tough.Mesh, but it can only be used on the grid with a cube border. Sometimes I have to delete some elements and their connection and it induces the shape of grid to become irregular, and the modified ’MESH‘ file cant be convert to tough.Mesh because of `ValueError: Input points do not form a structured grid.`. I usually use and change grid that is generated by Webmeshmaker, if I can generate grid and delete some useless grid by [tough.meshmaker()](url).

**Comment by keurfonluu** [comment]
Have you tried the function `toughio.meshmaker.triangulate` recommended for any MESH?

```python
import toughio

mesh_inp = toughio.read_mesh("MESH", file_format="tough")
points = [v["center"] for v in mesh_inp["elements"].values()]
mesh = toughio.meshmaker.triangulate(points)
mesh.plot(show_edges=True)
```
