### ISSUE TITLE
convert TOUGH2 output to TOUGH3 OUTPUT_ELEME.csv file

### ISSUE THREAD

**Issue by saharbakhshian** [keurfonluu/toughio#127]
Hello, 

I've used the following command in Anaconda prompt to convert the OUTPUT file into a mesh file (.csv):

toughio-extract OUTPUT MESH

However, I keep getting this error: "'toughio-extract' is not recognized as an internal or external command,
operable program or batch file."

Toughio library has been installed. 

I would appreciate your help.

**Comment by keurfonluu** [comment]
Is ``toughio`` installed in the same Python environment as your Anaconda Prompt (usually "base")?

**Comment by saharbakhshian** [comment]
Yes. It has been installed in the same Python environment. I'm able to import the package in Python and generate the mesh. However, I cannot extract the output file using toughio-extract.

**Comment by keurfonluu** [comment]
Can you check if "C:\Users\YOUR_USER_NAME\anaconda3\Scripts" is appended to your PATH?

**Comment by saharbakhshian** [comment]
Hi, 

I managed to finally install toughio properly and extract the OUTPUT file. First, I uninstall the package from Anaconda and reinstall it through Git Bash using the following command: 
pip install toughio[full] 

And it magically worked.

**Comment by keurfonluu** [comment]
Great!

Although, if your Anaconda distribution is properly set up, it should work as well.

**Comment by saharbakhshian** [comment]
Hello, 
I plan to create structured mesh in a dipping structure using meshmaker. When the dipping angle is zero, I use the following to generate the mesh:
mesh = toughio.meshmaker.structured_grid(dx, dy, dz) 

If I want to assign a dipping angle, what command should I use?

**Comment by keurfonluu** [comment]
Hi @saharbakhshian,

Please see answer posted in issue #147 (and continue there).
