### ISSUE TITLE
Visualization of OUTPUT_CONNE and MESH code name

### ISSUE THREAD

**Issue by nwpro9** [keurfonluu/toughio#137]
**Description of the desired feature**

**1 - Visualization of OUTPUT_CONNE.** Is it possible to export the connections output into visualization file (e.g., xdmf)? I found the ```toughio-export``` useful for elements output. I tried this for OUTPUT_CONNE file, but to no avail. Did I not use the right command or is this currently not supported? This is the command that I used: (I tired assigning different options like -f and -m with the corresponding records, but to no avail) ```toughio-export OUTPUT_CONNE.csv```

**2 - Incorporating MESH name (Format A5) to tough-export.** In addition, is it possible to infuse the MESH element code name into the visualization file generated from ```toughio-export```? I'm referring to the TOUGH element name with the format A5. So far, when I want to find the element name, I have to use the ```mesh.labels``` function from the script, but I'd have to know exactly which point I'm interested in to use this function. Any tips / advice?

**Are you willing to help implement and maintain this feature?** No

**Comment by keurfonluu** [comment]
Hi @nur-wijaya,

1. So far it's not supported, but I guess it shouldn't be too hard to implement (in Python, you can read connection data using `toughio.read_output` as well).

2. That wouldn't be possible as most mesh formats like VTK (if not all) only support numerical data. You can use the method `mesh.near` to find the index (thus the label) of the element nearest to the queried coordinate.
