### ISSUE TITLE
MESH PREPROCESSING USING mesh.write_tough() 

### ISSUE THREAD

**Issue by medhay36** [keurfonluu/toughio#140]
hello toughio users and experts 

i am trying to use toughio to prepare a complex radioative waste cell problem.

i prepared a mesh using gmsh and imported it successfully in toughio.

i would like to perform some operations such as affecting materials and BCs 

is there any examples to do so ?

**Comment by keurfonluu** [comment]
Hi @medhay36,

You can find some examples in the documentation: https://keurfonluu.github.io/toughio/examples/index.html
