### ISSUE TITLE
TIMBC block 

### ISSUE THREAD

**Issue by medhay36** [keurfonluu/toughio#145]
hello dear @keurfonluu

can you help me please with time boundary conditions TIMBC ??

I successfully generated the list of dictionnaries containing the TIMBC but I couldn't generate correctly the INFILE containing this BLOCK *
![image](https://github.com/keurfonluu/toughio/assets/122643918/01f372d4-e86d-4edd-a40b-89365d3ec3d3)

**Comment by keurfonluu** [comment]
Hi @medhay36,

Which version are you using? Please make sure you are using the latest: ``pip install toughio -U``.

**Comment by medhay36** [comment]
> Hi @medhay36,
> 
> Which version are you using? Please make sure you are using the latest: `pip install toughio -U`.

I was using version .11. I updated towards .13 and generation of the block worked fine.

There is a slight difference in the fortran format written in the INFILE for this block (doesn't match the TOUGH manual description)  but code runs successfully. 



![image](https://github.com/keurfonluu/toughio/assets/122643918/1331c244-caf9-4933-ab4d-2b80b68ca1f6)



There is a new problem with this update. The command line toughio-extract doesn't work anymore. I tried with files that the command was working perfectly with the previous version of toughio. 

Should I update something in the source code to match a certain output format ? 

 
![image](https://github.com/keurfonluu/toughio/assets/122643918/2b55e176-d2b7-474a-bc50-55716a73fac3)

**Comment by keurfonluu** [comment]
Hi @medhay36,

Can you provide the output and mesh file that don't work? ``toughio-extract`` still work for me.

**Comment by medhay36** [comment]
Hello dear @Keurfonluu,

I hope you are doing well.

Please find the requested files attached.

For info, things work very well until version 11.4 but from v 12. I
encountered the error.


Best regards
[OUT.zip](https://github.com/keurfonluu/toughio/files/12328027/OUT.zip)

**Comment by keurfonluu** [comment]
It's fixed now. Please update to version 1.13.1: ``pip install toughio -U``.

**Comment by medhay36** [comment]
> It's fixed now. Please update to version 1.13.1: `pip install toughio -U`.

hello again dear @keurfonluu 

problem is solved in generation of blocks and in postprocessing extraction 

but for reading a ready infile generated previously in which the block TIMBC has been genrated by another software it seems that there is a problem 

parameters = toughio.read_input("INFILE")

 
![image](https://github.com/keurfonluu/toughio/assets/122643918/54cbff61-e85a-43b9-bb22-f6091d77231f)


here what the TIMBC in question is structured  

![image](https://github.com/keurfonluu/toughio/assets/122643918/0a37897d-70bb-48ee-9fb3-384e7d808a09)

please find attached  the infile in question 
[INFILE.zip](https://github.com/keurfonluu/toughio/files/12385579/INFILE.zip)

**Comment by keurfonluu** [comment]
Are you sure you have correctly updated ``toughio``? I have no issue reading the attached file.

Looking at the failing line, it doesn't seem to match with the last version of ``toughio`` (in version ``1.13.1``, the function ``_read_timbc(f)`` starts at line 889). It seems that you are using version ``1.12.2`` (which had a bad TIMBC parser).

**Comment by medhay36** [comment]
> Are you sure you have correctly updated `toughio`? I have no issue reading the attached file.
> 
> Looking at the failing line, it doesn't seem to match with the last version of `toughio` (in version `1.13.1`, the function `_read_timbc(f)` starts at line 889). It seems that you are using version `1.12.2` (which had a bad TIMBC parser).

sorry dear @keurfonluu . you are right . Problem solved and parsing works fine after the new update
