### ISSUE TITLE
Can I export the mesh as .inp then use ToughIO or it only support VTK

### ISSUE THREAD

**Issue by miraboreasumr** [keurfonluu/toughio#148]
Please forgive me for putting question here, so what file I should export using Gmsh, inp?

**Comment by keurfonluu** [comment]
``msh`` is preferrable if you are exporting from Gmsh.

**Comment by miraboreasumr** [comment]
> `msh` is preferrable if you are exporting from Gmsh.

@keurfonluu 
All good, thanks!
