### ISSUE TITLE
How can I read TOUGH2 output file ?

### ISSUE THREAD

**Issue by BourbonTiger** [keurfonluu/toughio#149]
**How can I read TOUGH2 output file ?**

I saw that the toughio can read TOUGH3 output file and plot the result by pyvista but can toughio read Tough2 output file? I haven`t find the function

**Comment by keurfonluu** [comment]
``toughio.read_output`` works with outputs generated by TOUGH2, iTOUGH2, T2WELL, and TOUGH3.

**Comment by BourbonTiger** [comment]
But when i use toughio.read_output to read a flow.out file ,it report error. do i need to covert .out file to other format ? thanks!

**Comment by keurfonluu** [comment]
Can you attach your output file?

**Comment by BourbonTiger** [comment]
thank you! it,s report error because of the format of the content of the .out file , now It work well!
