### ISSUE TITLE
Is toughio compatible with TOUGH-MP output-files ?

### ISSUE THREAD

**Issue by geowomen** [keurfonluu/toughio#157]
Thank you for the great work !
--> I want to know if Toughio is compatible with TOUGH-MP output-files ??

**Comment by keurfonluu** [comment]
Hi @AMRIABDELLAH,

Unless TOUGH2-MP has different input and output formats compared to TOUGH2 and TOUGH3, I don't see any reason why ``toughio`` would not be compatible.

**Comment by geowomen** [comment]
Merci Keurfinluu !
