### ISSUE TITLE
Read and refine the mesh within certain materials.

### ISSUE THREAD

**Issue by geowomen** [keurfonluu/toughio#158]
Hello,
Thank you very much for Toughio; it's truly very useful. 
I have read a mesh using Toughio (MESH file or INPUT file). My goal is to refine the mesh within certain materials. Is this achievable? For instance, selecting a material and increasing the number of mesh elements. Or, selecting elements and splitting them into several elements.

Thank you for your replay.

Sincerly

**Comment by keurfonluu** [comment]
Hi @geowomen,

Remeshing is a whole other mathematical problem that ``toughio`` does not handle (it's not its purpose). Not to forget that TOUGH's MESH files do not hold the actual geometry mesh data that would be needed for remeshing.
