### ISSUE TITLE
Is Toughio ok or i'm doing the wrong things

### ISSUE THREAD

**Issue by geowomen** [keurfonluu/toughio#159]
Hello,
i'm doing it wrong i'm reading a mesh file from TOUGH2.  
Using : mesh = toughio.read_mesh(
   "MESH")
 and i'm getting a dictionnary insted of toughio.mesh data 

see the attached image 
![toughio_dic_return_insted_of_toughio_mesh_object](https://github.com/keurfonluu/toughio/assets/43623307/de04388a-a28f-4c33-9f32-e990b6cc86af)

**Comment by keurfonluu** [comment]
Hi @geowomen,

It's expected. TOUGH's MESH files do not hold the geometrical data of the mesh (points, cell connectivity...) to produce a ``toughio.Mesh`` object. TOUGH's MESH files only contain the volumes and centroids of each element, the interface areas and nodal distances of the connections, which are not enough to find the original mesh.
