### ISSUE TITLE
READ THE FLUX PART of The output file

### ISSUE THREAD

**Issue by geowomen** [keurfonluu/toughio#162]
Hello everyone,

I am currently using the `toughio.read_output` method to read the output of a TOUGH simulation. However, the data I obtain contains only the pressure (P), saturation (S), temperature (T), etc. I am interested in obtaining the flux by connection as well. Is there a way to achieve this?

Thanks for your support,
AA

**Comment by keurfonluu** [comment]
Hi @geowomen,

You need to set `connection` to True.

```python
outputs = toughio.read_output(filename, connection=True)
```

**Comment by geowomen** [comment]
Merci Keurfonluu
