### ISSUE TITLE
JOSS Review: Community guidelines

### ISSUE THREAD

**Issue by rreinecke** [keurfonluu/toughio#53]
Please address: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by rreinecke** [comment]
openjournals/joss-reviews/issues/2412

**Comment by keurfonluu** [comment]
Thanks for the comment! I've added contributing guidelines and templates for issues and pull requests.

**Comment by rreinecke** [comment]
Great. Looks like this also closes #52
