### ISSUE TITLE
Automated tests missing

### ISSUE THREAD

**Issue by ma-sadeghi** [keurfonluu/toughio#59]
I couldn't find a reference to automated testing in your package. If that's the case, you can easily set it up using Gtihub Actions or other services like Travis-CI.

**Comment by keurfonluu** [comment]
Hi,

As described in the README, you can run `pytest` locally to automatically test the package. Automatic tests are run on pull request on GitHub Actions, and documentation is built and deployed on Travis CI.

**Comment by ma-sadeghi** [comment]
Sorry, I didn't know you already set up Github Actions.

A suggestion: I think it would be nice to put the CI badge in your README file. I already found the url for your repo:
https://github.com/keurfonluu/toughio/workflows/Python%20package/badge.svg

**Comment by keurfonluu** [comment]
I've added a build badge (customized with shields.io to be consistent with the other badges, though).

**Comment by ma-sadeghi** [comment]
Great, thanks!
