### ISSUE TITLE
Store deploy key as a Github secret

### ISSUE THREAD

**Issue by ma-sadeghi** [keurfonluu/toughio#61]
The deploy key is hard-coded in the repo. Github has a way of storing these sorts of info (Settings -> Secrets).

**Comment by keurfonluu** [comment]
Hi,

The deploy key is for `doctr` to automatically deploy the doc once it is successfully built on Travis CI. Unfortunately, it seems that handling of secret keys have not been implemented yet (see https://github.com/drdoctr/doctr/issues/348).

The most up-to-date [doc](https://drdoctr.github.io/) still ask to commit the deploy key file, so I guess it is still not implemented:

> `doctr configure` will create a new file that contains your key. Commit this as well as the changes to `.travis.yml`. Once you push to GitHub, travis should now automatically build your documentation and deploy it.
