### ISSUE TITLE
Convert TOUGH2 output to VTK

### ISSUE THREAD

**Issue by geowomen** [keurfonluu/toughio#71]
**Description of the desired feature**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by geowomen** [comment]
First i want  to thank you for sharing your new Tools, I want to know if there is a way to use TOUGHIO with TOUGH2 and how ??

**Comment by keurfonluu** [comment]
Hi @AMRIABDELLAH,

Yes, ``toughio`` is compatible with TOUGH2. What do you want to do more explicitly?

You can find a tutorial that details its main features here: https://keurfonluu.github.io/toughio/examples/co2_leakage_along_a_fault/index.html

**Comment by geowomen** [comment]
Thanks for your replay,
I have a look at this tutorial, but the file OUTPUT_ELEM.csv can't be found in the TOUGH2 outputs so what file will replace the OUTPUT_ELEM??

**Comment by geowomen** [comment]
I want to transform my result for visualisation in format VTK

**Comment by keurfonluu** [comment]
I understand.

On which platform are your running TOUGH2?

**Comment by geowomen** [comment]
I'm compiling the TOUGH2 Code with gfortran on windows ??

**Comment by keurfonluu** [comment]
I guess that you installed Anaconda's Python distribution, right? Normally, if everything is set up correctly, you should be able to use the programs `toughio-extract` and `toughio-export` from a terminal to convert your TOUGH2 output files.

For instance, if you ran your TOUGH2 simulation with the command:

```bash
xt2_eos1.exe < INFILE > OUTPUT
```

You can convert the file OUTPUT to a TOUGH3 OUTPUT_ELEME.csv file by calling:

```bash
toughio-extract OUTPUT MESH
```

Then, you can use ``toughio-export`` to convert the generated OUTPUT_ELEME.csv file to a VTK file:

```bash
toughio-export OUTPUT_ELEME.csv
```

Note that these commands must be run from a console/terminal, they are **NOT** Python functions.

**Comment by geowomen** [comment]
Thank you Keurfonluu, i will will try, this suggestion,

**Comment by geowomen** [comment]
Hello Keurfonluu, i follow your suggestion and   when i run the follow comand :  >toughio-extract calculpe00.tec MESH
i get :



Traceback (most recent call last):
  File "c:\users\abdel\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\abdel\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\Scripts\toughio-extract.exe\__main__.py", line 7, in <module>
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_cli\_extract.py", line 43, in extract
    output = read_output(
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_io\output\_helpers.py", line 94, in read
    return _reader_map[file_format](
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_io\output\tecplot\_tecplot.py", line 39, in read
    for _ in range(zone["I"]):
UnboundLocalError: local variable 'zone' referenced before assignment



or when i run toughio-extract calculpe00.out MESH i get 



Traceback (most recent call last):
  File "c:\users\abdel\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\abdel\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\Scripts\toughio-extract.exe\__main__.py", line 7, in <module>
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_cli\_extract.py", line 43, in extract
    output = read_output(
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_io\output\_helpers.py", line 89, in read
    file_type, file_format = get_output_type(filename)
  File "C:\Users\abdel\AppData\Roaming\Python\Python38\site-packages\toughio\_io\output\_helpers.py", line 58, in get_output_type
    raise ValueError()
ValueError

**Comment by geowomen** [comment]
I use your OUTPUT_ELEM.csv file and it works, so can you please send me the two Line of TOUGH3, where i can add to my iTOUGH file and compite to have as an OUTPUT the  'OUTPUT_ELEM.csv' file ??? 
Thanks Keurfonluu,

**Comment by keurfonluu** [comment]
> Hello Keurfonluu, i follow your suggestion and when i run the follow comand : >toughio-extract calculpe00.tec MESH
i get

`toughio-extract` only works with standard TOUGH output file. For Tecplot output files, you should be able to run:

```
toughio-export calculpe00.tec
```

> or when i run toughio-extract calculpe00.out MESH i get

Can you attach your _calculpe00.out_ file here?

> I use your OUTPUT_ELEM.csv file and it works, so can you please send me the two Line of TOUGH3, where i can add to my iTOUGH file and compite to have as an OUTPUT the 'OUTPUT_ELEM.csv' file ???

Not sure whether the CSV format is available in iTOUGH2. In TOUGH3, it's the default output format, but you can also add a block `OUTPU`:

```
OUTPU----1----*----2----*----3----*----4----*----5----*----6----*----7----*----8
CSV
```

**Comment by geowomen** [comment]
Thank you Keurfonluu, 
i succed to generate the OUTPUT_ELEME.csv by modification of the source coude of iTOUGH2, i just to ask if the vtk generated have all the times in a single VTK file ( i'm not used to work with  vtk i use python) ??

**Comment by keurfonluu** [comment]
What kind of modification did you do in iTOUGH2 to make it work?

VTK format can only have a single time step. You'd better export to XDMF to save all the time steps (which can be opened in ParaView):

```
toughio-export OUTPUT_ELEME.csv -f xdmf
```

**Comment by geowomen** [comment]
Thank you Keurfonluu , here some element of how to generate OUTPUT_ELEME if someone have the only TOUGH2 / iTOUGH version ! my problem is solved thanks ! 
OPEN(UNIT=31,file='OUTPUT_ELEM.csv',STATUS='UNKNOWN')
WRITE(31,3431) 
3431 format("              ELEM","                 X","                 Y","                 Z","             SAT_G","             SAT_L","             XHYDG","             XHYDL","             PSAT","             PCAP","             DGAS","             DLIQ"
"                  ","               (M)","               (M)","               (M)","               (-)")
WRITE(31,7731) SUMTIM
  7731 FORMAT('"','TIME [sec]  ',E13.6,'"' )	
	WRITE(31,3434) ELEM(N)(:IELL),XXYYZZ(N,IJKXYZ(1)),
     &        XXYYZZ(N,IJKXYZ(2)),XXYYZZ(N,IJKXYZ(3)),PAR(NLOC2+1),
     &        PAR(NLOC2L+1),PAR(NLOC2+NB+2),PAR(NLOC2L+NB+2),
     &        PRES,PAR(NLOC2L+6),PAR(NLOC2+4)

**Comment by keurfonluu** [comment]
Thanks!

Can you also attach your standard output file (the one you named _calculpe00.out_)? I'd like to investigate why `toughio` failed to guess the type (it works with output files produced by the version of iTOUGH2 that I have).

**Comment by geowomen** [comment]
[calculpe00.zip](https://github.com/keurfonluu/toughio/files/5117203/calculpe00.zip)

This is my output using iTOUGH2

**Comment by keurfonluu** [comment]
Thanks, but you attached your input file.

I'd need an output file that looks like this one: [OUTPUT.zip](https://github.com/keurfonluu/toughio/files/5115828/OUTPUT.zip) (which has been generated by TOUGH3, but TOUGH2 and iTOUGH2 also generate a similar output).

**Comment by geowomen** [comment]
[calculpe00.zip](https://github.com/keurfonluu/toughio/files/5117208/calculpe00.zip)  ( generated by iTOUGH2)

**Comment by keurfonluu** [comment]
Thanks! It's fixed now. Should work in the next update.

**Comment by geowomen** [comment]
Thank you Keurfonluu ! Great work !

**Comment by keurfonluu** [comment]
The fix has now been released to the public in the version `1.4.0`. You can update `toughio`:

```
pip install -U toughio --user
```

**Comment by ghost** [comment]
> I guess that you installed Anaconda's Python distribution, right? Normally, if everything is set up correctly, you should be able to use the programs `toughio-extract` and `toughio-export` from a terminal to convert your TOUGH2 output files.
> 
> For instance, if you ran your TOUGH2 simulation with the command:
> 
> ```shell
> xt2_eos1.exe < INFILE > OUTPUT
> ```
> 
> You can convert the file OUTPUT to a TOUGH3 OUTPUT_ELEME.csv file by calling:
> 
> ```shell
> toughio-extract OUTPUT MESH
> ```
> 
> Then, you can use `toughio-export` to convert the generated OUTPUT_ELEME.csv file to a VTK file:
> 
> ```shell
> toughio-export OUTPUT_ELEME.csv
> ```
> 
> Note that these commands must be run from a console/terminal, they are **NOT** Python functions.

Thanks for your help. I have tried to convert the OUTPUT file into excel format and I don't have any problem. I would like to know if  FOFT file (file of the results of the elements specified by the user) can be converted to excel file format.

Thanks in advance

**Comment by ghost** [comment]
> I guess that you installed Anaconda's Python distribution, right? Normally, if everything is set up correctly, you should be able to use the programs `toughio-extract` and `toughio-export` from a terminal to convert your TOUGH2 output files.
> 
> For instance, if you ran your TOUGH2 simulation with the command:
> 
> ```shell
> xt2_eos1.exe < INFILE > OUTPUT
> ```
> 
> You can convert the file OUTPUT to a TOUGH3 OUTPUT_ELEME.csv file by calling:
> 
> ```shell
> toughio-extract OUTPUT MESH
> ```
> 
> Then, you can use `toughio-export` to convert the generated OUTPUT_ELEME.csv file to a VTK file:
> 
> ```shell
> toughio-export OUTPUT_ELEME.csv
> ```
> 
> Note that these commands must be run from a console/terminal, they are **NOT** Python functions.

I have tried to use the above instructions and they work well with the default cases of T2Well. However, when I have tried to use the same method with my simulation using T2Well, the following message error appears.
----------------------------------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.19041.630]
(c) 2020 Microsoft Corporation. All rights reserved.

(base) C:\Users\instadm>cd C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run

(base) C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run>toughio-extract OUTPUT MESH
Traceback (most recent call last):
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\input\tough\_helpers.py", line 288, in str2float
    return float(s)
ValueError: could not convert string to float: '****'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\instadm\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\instadm\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\instadm\anaconda3\Scripts\toughio-extract.exe\__main__.py", line 7, in <module>
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_cli\_extract.py", line 43, in extract
    output = read_output(
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\output\_helpers.py", line 111, in read
    return _reader_map[file_format](
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\output\tough\_tough.py", line 19, in read
    headers, times, variables = _read_table(f, file_type, label_length)
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\output\tough\_tough.py", line 125, in _read_table
    tmp += reader(line)
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\output\tough\_tough.py", line 96, in <lambda>
    reader = lambda line: [str2float(x) for x in line.split()]
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\output\tough\_tough.py", line 96, in <listcomp>
    reader = lambda line: [str2float(x) for x in line.split()]
  File "c:\users\instadm\anaconda3\lib\site-packages\toughio\_io\input\tough\_helpers.py", line 292, in str2float
    return float("{}e{}".format(significand, exponent))
ValueError: could not convert string to float: 'e****'

(base) C:\T2Well-ECO2N_Executable_v1.02\T2Well-ECO2N_Samples\Wellbore Temperature Modeling\Simulation run>
