### ISSUE TITLE
How to convert FOFT file output from T2Well into excel file format using toughio

### ISSUE THREAD

**Issue by ghost** [keurfonluu/toughio#82]
**Description of the desired feature**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by ghost** [comment]
I am new user of T2Well. I need to convert the output file generated by T2Well to excel file format using toughio. I could convert OUTPUT file into excel format using the following command line in prompt.

toughio-export OUTPUT_ELEME.csv

**Comment by keurfonluu** [comment]
Hi,

I don't use T2Well, but aren't FOFT files CSV-like (meaning that Excel should be able to open it without conversion)?
May you attach the file you wish to convert?

**Comment by ghost** [comment]
> Hi,
> 
> I don't use T2Well, but aren't FOFT files CSV-like (meaning that Excel should be able to open it without conversion)?
> May you attach the file you wish to convert?

Sure. Thanks for your reply. Attached is a link of FOFT file as output from T2Well. I have tried to attach it but I find the following message "We don't support that file type". 
https://www.dropbox.com/s/njmy9t8jjx2a9gf/FOFT?dl=0

**Comment by keurfonluu** [comment]
You can rename your file FOFT to FOFT.csv, Excel should be able to read as a comma-separated CSV file.

**Comment by keurfonluu** [comment]
This issue seems to be resolved. Add a comment if not to have it reopened.
