### ISSUE TITLE
How to modify the nodal distances using toughio?

### ISSUE THREAD

**Issue by ghost** [keurfonluu/toughio#83]
**Description of the desired feature**

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by ghost** [comment]
I want to modify the nodal distance of grids located in the uppermost layer using toughio. I have the following piece of code that enables me to modify the volume of the uppermost layer grids.

```python
import toughio

# Read file with block ELEME (e.g. MESH)
parameters = toughio.read_input("MESH")

# Loop over elements
for label, element in parameters["elements"].items():
    x, y, z = element["center"]

    # Assign material name depending on element's depth
    if z == -5.000e+01:
        element["volume"] *= 1.0e50
    # and so on

# Write your file back with modified materials
toughio.write_input("MESH", parameters)
```

I would like to know if there is a code that can modify the nodal distances in (z-direction) for grids located in that layer without the need to modify them manually.

**Comment by keurfonluu** [comment]
Hi,

The nodal distance is the distance between the center of the cell/element and its common interface with its neighboring cell/element. Unless you are applying Dirichlet boundary conditions to their neighboring elements, there is no reason to modify the nodal distances. Is it what you are trying to do?

**Comment by ghost** [comment]
Yes. I want to specify Dirichlet boundary conditions at the uppermost layer which represent atmospheric conditions. I have specified large volume (*1E50 m3) to that layer. I want to know how to modify the nodal distances using toughio given the coordinates of the grid cell. 

Note: I need this to decrease the nodal distance in z-direction for the uppermost layer.

**Comment by keurfonluu** [comment]
Okay, the trick is that nodal distances are located in `CONNE` block, so we have to loop over all the connections once we have identified the boundary elements.

```python
import toughio

# Read file with block ELEME (e.g. MESH)
parameters = toughio.read_input("MESH")

# Loop over elements
air = set()
for label, element in parameters["elements"].items():
    # Get coordinates of current element
    x, y, z = element["center"]

    # Assign huge volume to boundary elements and save their labels
    if z == -5.000e+01:
        element["volume"] *= 1.0e50
        air.add(label)

# Loop over connections
for label, connection in parameters["connections"].items():
    # Set nodal distance to 1.0e-9 if element is air
    if label[:5] in air:
        connection["nodal_distances"][0] = 1.0e-9
    elif label[5:] in air:
        connection["nodal_distances"][1] = 1.0e-9

# Write modified input file
toughio.write_input("MESH", parameters)
```

**Comment by ghost** [comment]
Got it. Thank you for your help. I have a question with the above code. Where do you define the type of connection (in z-direction here)in the above code? I think the code can also be used to define Dirichlet boundary conditions in the outer lateral boundaries of the reservoir, so in this case I need to decrease nodal distance in x and y directions (assuming xyz model).

**Comment by ghost** [comment]
I find after applying the code that all nodal distances for uppermost layer are decreased. I think I need to decrease the nodal distance in z-direction only for the uppermost layer grids.

**Comment by keurfonluu** [comment]
I guess that you can check the angle between the connection line and the gravity:

```python
# Loop over connections
for label, connection in parameters["connections"].items():
    is_vertical = abs(connection["gravity_cosine_angle"]) == 1.0
    # Set nodal distance to 1.0e-9 if element is air
    if label[:5] in air and is_vertical:
        connection["nodal_distances"][0] = 1.0e-9
    elif label[5:] in air and is_vertical:
        connection["nodal_distances"][1] = 1.0e-9
```

But it shouldn't matter actually.

**Comment by ghost** [comment]
Thank you!

**Comment by keurfonluu** [comment]
Feel free to close the issue if it is resolved!

**Comment by ghost** [comment]
Sorry for that, but I find the following error while running the above code.

Traceback (most recent call last):

  File "<ipython-input-40-ac609db09946>", line 19, in <module>
    is_vertical = connection["gravity_cosine_angle"] == 1.0

KeyError: 'gravity_cosine_angle'

**Comment by keurfonluu** [comment]
Can you attach the file you are trying to edit?

**Comment by keurfonluu** [comment]
Okay, I guess that your file does not have a gravity angle for all connections, but it should have a permeability direction:

```python
# Loop over connections
for label, connection in parameters["connections"].items():
    is_vertical = connection["permeability_direction"] == 3
    # Set nodal distance to 1.0e-9 if element is air
    if label[:5] in air and is_vertical:
        connection["nodal_distances"][0] = 1.0e-9
    elif label[5:] in air and is_vertical:
        connection["nodal_distances"][1] = 1.0e-9
```
