### ISSUE TITLE
Is TOUGHIO suitable for TOUGH+HYDRATE?

### ISSUE THREAD

**Issue by yanluding** [keurfonluu/toughio#86]
I am fairly new to TOUGH series programs. May I ask if toughio is suitable for TOUGH+HYDRATE?

**Comment by Alejobep** [comment]
Certain things can be done, however the Input files from T+H has some sections and parameters not implemented in TOUGH2/TOUGH3. Therefore you may find some limitations. You could still produce an input file in toughio and take care of the ELEME, CONNE, GENER and PARAM sections. However, the INCON becomes tricky.

**Comment by keurfonluu** [comment]
I am not a T+H user so currently, ``toughio`` does not fully support it (only TOUGH input file).
PR are welcomed, though.
