### ISSUE TITLE
Mesh Generation in T2Well

### ISSUE THREAD

**Issue by ghost** [keurfonluu/toughio#87]
**Description of the desired feature**

Hi,

I am a new user of T2Well/ECO2N. I want to start building my model by creating mesh using Meshmaker.  I would like to know how to build the mesh structure for T2Well simulation. Attached is an excerpt of the mesh that I want to generate which has to be the same as that used in T2Well/ECO2N manual - Example Problems (Case 1).

MESHMAKER1----*----2----*----3----*----4----*----5----*----6----*----7----*----8
RZ2D
RADII
    1
        0.
EQUID
    1             .1
LAYER----1----*----2----*----3----*----4----*----5----*----6----*----7----*----8
  100
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.       10.       10.       10.       10.
       10.       10.       10.       10.
		
ENDFI----1----*----2----*----3----*----4----*----5----*----6----*----7----*----8

**Comment by Alejobep** [comment]
Meshmaker has been built into toughio. Check out the Documentation pages
https://keurfonluu.github.io/toughio//examples/heat_pipe_in_cylindrical_geometry/1_preprocessing.html

**Comment by keurfonluu** [comment]
As stated by @Alejobep, ``toughio`` supports TOUGH's MESHMAKER inputs. Note that ``toughio.meshmaker.from_meshmaker`` accepts a filename as argument (instead of a dict as in the example).
