### ISSUE TITLE
Time for full-field scale results

### ISSUE THREAD

**Issue by mfg7** [keurfonluu/toughio#88]
Hi!

I love your module. But, I have only been able to use it for small models. I have a big, full-field scale model that I want to extract. I use the 2017 version of iTOUGH2. I use hexagonal Voronoi 2.5 grids with element sizes ranging from 200 (approx radius) to 1600 meters...
Just to be sure that I am doing everything alright, 
-Is the mesh file the same as the ELEME block and if so, does it include the ELEME title?
-Is the OUTPUT the file that iTOUGH2 creates with extension .out?
-Is there any limitation of size or typical time for a very big model to extract?

thanks in advance!!!

**Comment by keurfonluu** [comment]
Hi @mfg7 ,

- As far as I know, the `MESH` file formats are the same for all TOUGH2, iTOUGH2 and TOUGH3. `MESH` files consist of `ELEME` and `CONNE` blocks,
- I don't remember, but `OUTPUT` file in TOUGH3 is the log file with "TOUGH" written in ASCII (with @s). iTOUGH2 also produces a similar file. In TOUGH2, it's the `OUTPUT` file when running the command `tough2 < INFILE > OUTPUT`
- No limitation normally. I've run a problem with a mesh with 2 millions of cells.

**Comment by mfg7** [comment]
Thanks @keurfonluu 

I have not been able to succeed on extracting and thus the following steps to get my results into paraview. I get the following traceback when I try to run the toughio-extract with the OUTPUT as the inputfile.out file from itough results as renamed and MESH including only the ELEME and CONNE blocks. I have only ~6900 elements

 toughio-extract OUTPUT MESH
Traceback (most recent call last):
  File "/home/maria/.local/bin/toughio-extract", line 8, in <module>
    sys.exit(extract())
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_cli/_extract.py", line 36, in extract
    parameters = read_mesh(
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_mesh/_helpers.py", line 96, in read
    mesh = _reader_map[fmt](filename, **kwargs)
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_mesh/tough/_tough.py", line 20, in read
    mesh = read_input(filename, file_format="tough", label_length=label_length)
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_io/input/_helpers.py", line 80, in read
    return _reader_map[fmt](filename, **kwargs)
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_io/input/tough/_read.py", line 34, in read
    out = read_buffer(f, label_length)
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_io/input/tough/_read.py", line 120, in read_buffer
    parameters.update(_read_conne(fiter, label_length))
  File "/home/maria/.local/lib/python3.8/site-packages/toughio/_io/input/tough/_read.py", line 678, in _read_conne
    line = next(f)
StopIteration


What can I do to fix it? I would appreciate greatly your help again!

**Comment by keurfonluu** [comment]
I can't tell what's wrong without the output files. If you don't feel comfortable sharing your results here, you can send them to me by email.

**Comment by mfg7** [comment]
Perfect! Thanks! I just shared them from my email!

**Comment by keurfonluu** [comment]
@mfg7 In your MESH file, add a new line at the end of your file (such that you have 27642 lines instead of 27641). It's needed by both TOUGH and `toughio` to know when the block `CONNE` stops.

**Comment by mfg7** [comment]
Thanks! It worked.
One new question I have is, if having a 2
.5 Voronoi grid and want to see the results in paraview as xdmf (time changing) with the hexagons showing? I saw there is a vtkUnstructuredagrid kind of file

1. Should I use any specific option of toughio for this type of grid?
2. How does the xdmf time steps get selected? I did it and got an xdmf file with 7 time steps but I had over 500 set up to be calculated

**Comment by keurfonluu** [comment]
1. `toughio` relies on `meshio` for mesh inputs and outputs, yet `meshio` currently does not support polyhedron (e.g., 3D Voronoi cells). A polyhedron is rather hard to represent if it's only defined by its vertices. It may be possible to do that with `pyvista` (a VTK wrapper) but I haven't looked into it.

2. TOUGH only saves results for time steps defined in the block `TIMES`, these are the times that are considered when exporting to XDMF.
