### ISSUE TITLE
TOUGH MESH/INCON to toughio.Mesh

### ISSUE THREAD

**Issue by BinWang0213** [keurfonluu/toughio#91]
**Convert TOUGH MESH/INCON to toughio.Mesh**

I noticed that toughio can convert various 3rdParty mesh into TOUGH format. 
How can I reverse this process?

**Are you willing to help implement and maintain this feature?** No

**Comment by keurfonluu** [comment]
Hi @BinWang0213 ,

It depends on what you mean by reversing the process. If you want to get the original cell vertices from TOUGH cell centers, you obviously can't. If you just want to visualize your results, you can use `toughio.meshmaker.triangulate` to recreate another mesh from TOUGH cell centers, and then attach TOUGH results as point data (see [`toughio._cli._export.py`](https://github.com/keurfonluu/toughio/blob/6efdc2f4172bba3c89ec4a0aba6a1b7b157cb26a/toughio/_cli/_export.py#L130) for instance).

**Comment by BinWang0213** [comment]
@keurfonluu Thanks for your prompt reply. I'm new to TOUGH, I was thinking TOUGH's MESH file contains vertices, elements like Gmsh. So MESH file only contains cell centers? 

Could you share a simple code snippet to visualize the attached mesh files?
[test_mesh.zip](https://github.com/keurfonluu/toughio/files/7646958/test_mesh.zip)

* [Bug Report] Also, I can not read INCON file by `incon = toughio.read_mesh('INCON',file_format="tough")`

```
ValueError                                Traceback (most recent call last)
F:\Anaconda\lib\site-packages\toughio\_io\input\tough\_helpers.py in str2float(s)
    323     try:
--> 324         return float(s)
    325     except ValueError:

ValueError: could not convert string to float: 'e-0203.023'
```

Thanks,
Bin

**Comment by keurfonluu** [comment]
Here is a code snippet to reconstruct **a** mesh from any *MESH* file:

```python
import toughio

mesh_inp = toughio.read_mesh("MESH", file_format="tough")
points = [v["center"] for v in mesh_inp["elements"].values()]
mesh = toughio.meshmaker.triangulate(points)
mesh.plot(show_edges=True)
```

Your mesh seems to be a rectangular mesh, thus, you can actually reconstruct the original grid if you provide the correct `origin` (the function `toughio.meshmaker.voxelize` is able to recalculate the vertices of a hexahedral mesh given the coordinates of the cell centers and the coordinates of the origin):

```python
mesh = toughio.meshmaker.voxelize(points, origin=[0.0, 0.0, 0.0])
```

For the *INCON* file, you should use the function `toughio.read_input` instead. However, your input file does not seem to be standard, so it will actually fail. Are you sure your file is valid? According to TOUGH's user guide, the first record of each element must have the format (A3, I2, 2I5, E15.9, 5E10.4). The first record in your *INCON* file has the format (A3, I2, 2I5, 4E15.9), which should not be valid.

**Comment by BinWang0213** [comment]
It works great by using `mesh = toughio.meshmaker.voxelize(points, origin=[0.0, 0.0, 0.0])`. 

Thanks,
Bin

**Comment by jousheinfo** [comment]
Hi, I have a radial mesh and the function triangulate does not work for me. I have also tried to use cylindric_grid, but it still fails. What can I do, please?
