### ISSUE TITLE
'dict' object has no attribute 'to_meshio'

### ISSUE THREAD

**Issue by PerFoamer** [keurfonluu/toughio#94]
Hi keurfonluu,

i tried to convert a Tough mesh into a .vtk mesh to visualisize it in ParaView but i got the following error:

File "C:\Rechnungen\Toughio.py", line 13, in <module>
    toughio.write_mesh(
  File "C:\MyPython\toughio\toughio\_mesh\_helpers.py", line 181, in write
    mesh = mesh.to_meshio()
AttributeError: 'dict' object has no attribute 'to_meshio'

I attached the Tough mesh and the script to start the conversion.

Best regards 
Gerd 

[Toughio.txt](https://github.com/keurfonluu/toughio/files/7746748/Toughio.txt)
[Rechteck2MESH.txt](https://github.com/keurfonluu/toughio/files/7746753/Rechteck2MESH.txt)

**Comment by keurfonluu** [comment]
Hi @PerFoamer,

A TOUGH *MESH* file is represented as a dict by `toughio`, and not a standard `toughio.Mesh` as TOUGH *MESH* files do not have vertices. You can generate a `toughio.Mesh` object from a cloud points using the functions `toughio.meshmaker.triangulate` or `toughio.meshmaker.voxelize`, though (see issue #92).

**Comment by PerFoamer** [comment]
Hi keurfonluu,

thank your for the hint, my intention was to visualize the meshes from toughs native MESHMAKER v1.5. 
Thanks for your advice, i will try the toughio meshmaker.

Best regards 
Gerd
